#!/bin/bash
# Copyright 2021 Alibaba Group Holding Limited. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================

OUTDIR=$1
mkdir -p $OUTDIR
GLIBC=$(ldd --version | head -1 | awk '{print $NF}' | tr '.' '_')
PLATFORM="manylinux_${GLIBC}_x86_64"

set -eo pipefail

TFLIB=$(python -c "import tensorflow as tf; print(tf.sysconfig.get_lib())" 2>/dev/null)
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TFLIB} \
auditwheel repair --plat ${PLATFORM} cibuild/dist/*.whl -w ${OUTDIR}
