#!/bin/bash
# Copyright 2021 Alibaba Group Holding Limited. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================

if [[ -z "$DOCKER_BASE_IMAGE" ]]; then
  DOCKER_BASE_IMAGE=registry.cn-shanghai.aliyuncs.com/pai-dlc/hybridbackend:developer-nvtf1-py3.6-cu114-ubuntu18.04
fi

set -eo pipefail

DOCKERFILE="dockerfiles/Dockerfile.$(sed 's/.*\://g' <<< $DOCKER_BASE_IMAGE)"

cd cibuild/

sudo docker build -t ${DOCKER_BASE_IMAGE} -f ${DOCKERFILE} .

cd -

echo "Successfully built $DOCKER_IMAGE"
