#!/bin/bash
# Copyright 2021 Alibaba Group Holding Limited. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================

set -eo pipefail

HEADERS=$(find \( -path ./arrow -o -path ./sparsehash -o -path ./build -o -path ./dist \) -prune -false -o -type f -name '*.h')
SOURCES=$(find \( -path ./arrow -o -path ./sparsehash -o -path ./build -o -path ./dist \) -prune -false -o -type f -name '*.cc')

if [[ ! -z ${HEADERS} ]] || [[ ! -z ${SOURCES} ]]; then
    clang-format -i ${HEADERS} ${SOURCES}
fi
