#!/bin/bash
# Copyright 2021 Alibaba Group Holding Limited. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================

if [[ -z "$REPO" ]]; then
  REPO=registry.cn-shanghai.aliyuncs.com/pai-dlc/hybridbackend
fi

if [[ -z "$TAG" ]]; then
  TAG=tf1.15-py3.8-cu114-ubuntu20.04
fi
DOCKERIMAGE="${REPO}:developer-${TAG}"
DOCKERFILE="dockerfiles/Dockerfile.developer-${TAG}"
if [[ ! -f "env/${DOCKERFILE}" ]]; then
  echo >&2 "env/${DOCKERFILE} not found"
  exit 1
fi

set -eo pipefail

cd env/

DOCKER_BUILDKIT=1 docker build \
--build-arg BUILDKIT_INLINE_CACHE=1 \
--network host \
-t ${DOCKERIMAGE} -f ${DOCKERFILE} \
$@ .

cd -

echo "Successfully built ${DOCKERIMAGE}"
