name: cibuild on gpu for deeprec

on: [workflow_dispatch]

env:
  IMAGE: registry.cn-shanghai.aliyuncs.com/pai-dlc/hybridbackend:developer-deeprec-py3.6-cu114-ubuntu18.04
  JOBNAME: hbci-${{ github.run_id }}
  PODNAME: hbci-${{ github.run_id }}-chief-0

jobs:
  cibuild:
    runs-on: ubuntu-latest
    environment: deeprec-py3.6-cu114-ubuntu18.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup Environment
      uses: aliyun/ack-set-context@v1
      with:
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        cluster-id: "${{ secrets.ACK_CLUSTER_ID }}"
    - name: Upload
      run: |-
        helm install ${JOBNAME} cibuild/ \
        --set image=${IMAGE} \
        --set gpus=2 && \
        cibuild/upload ${PODNAME} ../cibuild
    - name: Build
      run: |-
        kubectl exec -it ${PODNAME} -- sh -c 'make -j32 HYBRIDBACKEND_WHEEL_ALIAS=-deeprec HYBRIDBACKEND_WHEEL_BUILD=rc${{ github.run_id }}'
    - name: Install
      run: |-
        kubectl exec -it ${PODNAME} -- sh -c 'PYTHONPATH= pip install cibuild/dist/*.whl'
    - name: Test
      run: |-
        kubectl exec -it ${PODNAME} -- sh -c 'PYTHONPATH= TEST_EXTRAS=deeprec make test'
    - name: Cleanup Environment
      if: always()
      run: |-
        helm uninstall ${JOBNAME}
